const admin = require("firebase-admin");
let firebaseReady=false;
function normalizeEmployeeKey(v){return String(v||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim().toLowerCase().replace(/\s+/g," ");}
function initializeFirebaseAdmin(){if(firebaseReady)return true;const projectId=String(process.env.FIREBASE_PROJECT_ID||"").trim();const clientEmail=String(process.env.FIREBASE_CLIENT_EMAIL||"").trim();const privateKey=String(process.env.FIREBASE_PRIVATE_KEY||"").replace(/\\n/g,"\n").trim();if(!projectId||!clientEmail||!privateKey){console.warn("⚠️ Firebase Push desactivado: faltan credenciales.");return false;}if(!admin.apps.length)admin.initializeApp({credential:admin.credential.cert({projectId,clientEmail,privateKey})});firebaseReady=true;console.log("✅ Firebase Push Notifications activado");return true;}
async function registerPushToken(query,p={}){const employeeName=String(p.employeeName||"").trim(),employeeRole=String(p.employeeRole||"").trim(),token=String(p.token||"").trim();if(!employeeName||!token)throw new Error("Falta el empleado o el token.");const employeeKey=normalizeEmployeeKey(employeeName);await query(`INSERT INTO push_device_tokens(employee_name,employee_key,employee_role,token,platform,user_agent,active,last_seen_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,TRUE,NOW(),NOW()) ON CONFLICT(token) DO UPDATE SET employee_name=EXCLUDED.employee_name,employee_key=EXCLUDED.employee_key,employee_role=EXCLUDED.employee_role,platform=EXCLUDED.platform,user_agent=EXCLUDED.user_agent,active=TRUE,last_seen_at=NOW(),updated_at=NOW()`,[employeeName,employeeKey,employeeRole,token,String(p.platform||"web"),String(p.userAgent||"").slice(0,1000)]);return{employeeName,employeeKey,employeeRole};}
async function deactivatePushToken(query,token){await query(`UPDATE push_device_tokens SET active=FALSE,updated_at=NOW() WHERE token=$1`,[token]);}
async function getPushStatus(query,employeeName){const key=normalizeEmployeeKey(employeeName);if(!key)return{registered:false,devices:0};const r=await query(`SELECT COUNT(*)::int devices,MAX(last_seen_at) last_seen_at FROM push_device_tokens WHERE active=TRUE AND employee_key=$1`,[key]);return{registered:(r.rows[0]?.devices||0)>0,devices:r.rows[0]?.devices||0,lastSeenAt:r.rows[0]?.last_seen_at||null};}
async function sendPushToEmployees(query,names,message={}){if(!initializeFirebaseAdmin())return{sent:0,failed:0,skipped:true,reason:"firebase-not-configured"};const keys=[...new Set((names||[]).map(normalizeEmployeeKey).filter(Boolean))];if(!keys.length)return{sent:0,failed:0,skipped:true,reason:"no-employees"};const r=await query(`SELECT token FROM push_device_tokens WHERE active=TRUE AND employee_key=ANY($1::text[])`,[keys]);const tokens=[...new Set(r.rows.map(x=>x.token).filter(Boolean))];if(!tokens.length)return{sent:0,failed:0,skipped:true,reason:"no-active-tokens"};const data=Object.fromEntries(Object.entries({title:String(message.title||"417 Maid OS"),body:String(message.body||"Tienes una actualización."),link:String(message.link||"/launch"),tag:String(message.tag||`417-${Date.now()}`),...(message.data||{})}).map(([k,v])=>[k,String(v??"")]));const response=await admin.messaging().sendEachForMulticast({tokens,data,webpush:{headers:{Urgency:message.urgent?"high":"normal"},notification:{title:data.title,body:data.body,icon:"/icons/icon-192.png",badge:"/icons/badge-96.png",tag:data.tag,renotify:Boolean(message.urgent),requireInteraction:Boolean(message.urgent)},fcmOptions:{link:data.link}}});const invalid=[],errors=[];response.responses.forEach((item,i)=>{if(item.success)return;const code=item.error?.code||"unknown";errors.push(code);if(["messaging/registration-token-not-registered","messaging/invalid-registration-token"].includes(code))invalid.push(tokens[i]);});if(invalid.length)await query(`UPDATE push_device_tokens SET active=FALSE,updated_at=NOW() WHERE token=ANY($1::text[])`,[invalid]);return{sent:response.successCount,failed:response.failureCount,invalidTokens:invalid.length,errors:[...new Set(errors)]};}
module.exports={initializeFirebaseAdmin,registerPushToken,deactivatePushToken,getPushStatus,sendPushToEmployees,normalizeEmployeeKey};
